version: '3.8'

services:
  # node-app:
  #   container_name: node-app
  #   build: .
  #   ports:
  #     - '5000:5000'
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   depends_on:
  #     - db
  #   environment:
  #     - DB_HOST=db
  #     - DB_USER=root
  #     - DB_PASSWORD=root
  #     - DB_NAME=tutorial
  #   networks:
  #     - app-network

  db:
    container_name: mysql-db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tutorial
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - '3306:3306'

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db-data:


networks:
  app-network:
